
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: toze25/gestao-estagios:1.0.0
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: gestao-estagios
      DB_USERNAME: admin
      DB_PASSWORD: root

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:5.7
    ports:
      - "3308:3308"
    environment:
      MYSQL_DATABASE: gestao-estagios
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:18 
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["npm", "run", "dev"] 
    ports:
    - "5173:5173"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data: