version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cesardaniel15/gestao-estagios:1.0.0
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=gestao-estagios
      - DB_USERNAME=admin
      - DB_PASSWORD=root

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: gestao-estagios
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: