version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:80"  # Acesso ao Laravel
      - "5173:5173"  # Porta padrão do Vite
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:L2O8ReB3dYCGtO5BCJb2q45xmdSbiYih4rStI1F1/XY=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=gestao_estagios
      - DB_USERNAME=root
      - DB_PASSWORD=admin
      - ADMIN_CODE=24680

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: gestao_estagios
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
